### PR TITLE
Fixes required for OSX + clang 3.6.0

### PR DESCRIPTION
**Pull request by aharrison24**
These commits contain changes necessary to build on OSX. I won't claim that they are 'correct' solutions to the problems I faced, but they should at least give pointers to what the problem is, and you can then come up with better fixes where appropriate.

Notes:
- I only worked with the CMake build.
- The 'runtest' target still does not build because TEST_DEVICE is not defined. I haven't looked in to this.
- I'm on OSX 10.9, using a hand-rolled clang 3.6.0. Haven't yet tested with the default clang that comes with XCode.

### CODE REVIEW

**Comment by naibaf7** [comment]
I am not quite sure why you (have to?) exclude certain explicit instantiations? They are supposed to work like they were...

**Comment by aharrison24** [comment]
Here's a flavour of the linker errors I get with clang (both 3.6.0 and the
'default' XCode clang):
https://gist.github.com/aharrison24/a38a5ff417b5c67f0247

I haven't been able to find much on this through googling, but this link
gives a hint that maybe duplicate explicit instantiation is an 'extension'
allowed by MSVC (and clang when in MSVC compatibility mode, as it normally
is on Windows platforms).
http://lists.cs.uiuc.edu/pipermail/cfe-commits/Week-of-Mon-20140505/105205.html

The C++ Standard _appears_ to be quite clear on this (though I'm well out
of my depth here):
14.7.5.1 For a given template and a given set of template-arguments, an
explicit instantiation definition shall appear at most once in a program,

(You can find this at the bottom of page 379:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf )

**Comment by aharrison24** [comment]
Just to be clear, I'm compiling without CUDA, so USE_CUDA is false and USE_GREENTEA is true. Which means the <layer>.cu files are being 'included' into the <layer>.cpp files. The result is that the invocations of 'INSTANTIATE_CLASS' and 'INSTANTIATE_LAYER_GPU_FUNCS' are happening in the same compilation unit. In the upstream repo, those macros don't get used together in a single compilation unit.

**Comment by aharrison24** [comment]
Rather than having blocks like:
#if defined(USE_GREENTEA) && !defined(USE_CUDA)
#include "power_layer.cu"
#endif

...perhaps the '.cu' files should just be compiled standalone and linked as usual, as if they were cpp files. That way you could let the linker remove the dupes and you wouldn't need the preprocessor trickery.

Important caveat if you're doing this in CMake:
http://stackoverflow.com/questions/18784811/cmake-and-non-standard-extensions

**Comment by naibaf7** [comment]
@aharrison24 
I fixed .cu compilation now. Try if it works for you.

**Comment by aharrison24** [comment]
Yes, all seems good now.

Still can't build the 'runtest' target though, because TEST_DEVICE isn't
defined for the CMake build.

**Comment by naibaf7** [comment]
@aharrison24 
OK, that seems to be an inherited bug from the original caffe, or should be easy enough to fix either way. I'll look into it when I find time. Or you can fix it if you want ;)

**Pull request closed without merging**
